// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAX2tiKprQ76Xz8HhOPj8R54lKhqPIkTk',
    appId: '1:135210622306:web:2bd175452cd0fd39aa203b',
    messagingSenderId: '135210622306',
    projectId: 'meme-bcb1e',
    authDomain: 'meme-bcb1e.firebaseapp.com',
    databaseURL: 'https://meme-bcb1e-default-rtdb.firebaseio.com',
    storageBucket: 'meme-bcb1e.firebasestorage.app',
    measurementId: 'G-F63V95JR7Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDa12_B2dt2mm7_ugvHmIDi84wU8G0Pz1s',
    appId: '1:135210622306:android:c3a255e9fe7bf547aa203b',
    messagingSenderId: '135210622306',
    projectId: 'meme-bcb1e',
    databaseURL: 'https://meme-bcb1e-default-rtdb.firebaseio.com',
    storageBucket: 'meme-bcb1e.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAX2tiKprQ76Xz8HhOPj8R54lKhqPIkTk',
    appId: '1:135210622306:web:818afeee562cd3a6aa203b',
    messagingSenderId: '135210622306',
    projectId: 'meme-bcb1e',
    authDomain: 'meme-bcb1e.firebaseapp.com',
    databaseURL: 'https://meme-bcb1e-default-rtdb.firebaseio.com',
    storageBucket: 'meme-bcb1e.firebasestorage.app',
    measurementId: 'G-0BFNC7R8EM',
  );

}